version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: "637423476845"
    AWS_DEFAULT_REGION: "ap-south-1"
  secrets-manager:
    AWS_ACCESS_KEY_ID: "arn:aws:secretsmanager:ap-south-1:637423476845:secret:access-keys-zwiv9K:AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "arn:aws:secretsmanager:ap-south-1:637423476845:secret:access-keys-zwiv9K:AWS_SECRET_ACCESS_KEY"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm i -g mocha && npm i --legacy-peer-deps
      - echo Verifying Node.js and npm installation
      - node -v
      - npm -v

  pre_build:
    commands:
      - echo Configuring AWS CLI
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region $AWS_DEFAULT_REGION

  build:
    commands:
      - cd cdk-test
      - npm install
      - npx cdk deploy --require-approval never

artifacts:
  files:
    - '**/*' 
